### ISSUE TITLE
Reimplementation issue

### ISSUE THREAD

**Issue by abcdvzz** [zengkaipeng/UAlign#1]
Hi authors, thank you for your work. I am trying to reproduce your work. Could you please upload the checkpoint to the google drive because there are no checkpoints right now. In addition, could you please share me with your hyperparameters that passed to the pretrain.py and trans.py? I think there are some typos in the readme. The first stage is pretrain.py and the second is trans.py, am I right?

**Comment by zengkaipeng** [comment]
yes, thanks for the reminder, the second stage should be train_trans.py and the checkpoints is uploaded to the google drive right now.

**Comment by abcdvzz** [comment]
Can you also provide us with the training hyperparameters? I tried to train the model but it seems it doesn't converge.

**Comment by zengkaipeng** [comment]
The inquirer has already communicated with me via email, so there is no need for further questions in this issue, hence I have closed it.
