### ISSUE TITLE
Inference mode on retrosynthesis

### ISSUE THREAD

**Issue by thegodone** [zengkaipeng/UAlign#3]
I have a question regarding the retrosynthesis logic using inference_one.py : 
- how to prepare our data when you don't know the reaction ?
If you have only the product and don't know the reactant we cannot align. So how to apply on real cases where the goal is to predict the reactant from the product ?

**Comment by zengkaipeng** [comment]
In the file `inference.py`, on line 154, during the inference process, we have removed the atom mapping information and converted the product SMILES into its canonical form. The generation of this canonical SMILES is related only to the product itself, and you do not need to prepare reactant and corresponding reaction information. More specifically, during the inference, the DFS order fed to the model is the DFS order for generating the canonical SMILES of the product, which is solely related to the product itself. The alignment is only used for labeling during training.

If you wish to perform inference with your own data, you have two options.

1. You can organize your data to resemble the processed dataset we provide, placing the product in the "reactants>reagents>production" column as "{}>>product SMILES", where "{}" can be anything. Our inference script can accept inputs without atom mapping or even chemical reactions with empty reactants without errors, as long as the product SMILES is valid. The "id" and "class" columns can also be filled in randomly, as long as the headers exist. Then, by following the commands written in the README to call `inference.py`, you will be able to obtain the model's predictions.

2. If your dataset is not very large, you can also call `inference_one.py` according to the commands in the README to get the model's retrosynthesis prediction for a single reaction (or product). This script only requires you to provide the product SMILES as input to operate.

If you have any further questions, please feel free to ask me.


For example, if you wish to use the checkpoint obtained from training on the USPTO_FULL dataset to perform retrosynthesis prediction on the compound `CC(Nc(c1)nc2n1nc(I)cc2)=O`, you can use the following command to obtain the results. The command and the results are shown in the attached figure.

![1722937494975](https://github.com/user-attachments/assets/29cca3f8-fae0-4dd1-a6b0-5307f37c5f22)

**Comment by thegodone** [comment]
thank you for the clarification. really helpfull and for the code & model dev!
